language: haxe
haxe: development
dist: bionic

install:
  - git config --global gc.auto 0 # we will call gc manually during deploy
  - haxelib install all --always
  - haxelib install hxcpp 4.0.52 --always
  - haxelib set hxcpp 4.0.52 --always
  - haxelib dev hxparse libs/hxparse
  - haxelib dev hxtemplo libs/hxtemplo
  - haxelib dev hxargs libs/hxargs
  - haxelib dev markdown libs/haxe-markdown
  - haxelib dev dox libs/dox
  - haxelib list

script:
  - haxe gen.hxml
  - neko Gen.n
  # validate html
  - wget -q https://github.com/validator/validator/releases/download/18.8.29/vnu.jar_18.8.29.zip
  - unzip vnu.jar_18.8.29.zip
  - java -jar dist/vnu.jar --errors-only html/*.html # only for the top level html for now since there are many errors in e.g. js/html/*.html

deploy:
  provider: script
  script: haxe --run DeployGhPages
  on:
    branch: master
  skip_cleanup: true
